<a href="https://colab.research.google.com/github/raigao1/Cadastros/blob/master/Relatorio2_BrunoBarcellos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Bibliotecas**

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import math
from numpy import array, zeros

**Exercicio 1**



Resolva o SELA pelo método de Eliminação de Gauss sem pivotamento e com
pivotamento parcial, retendo, durante as eliminações, cinco algarismos depois da
vírgula. Compare os resultados.

x2 + 3x3 + 2x4 + 4x5 = 3 

8x1 - 2x2 + 9x3 - x4 + 2x5 = -5

5x1 + x2 + x3 + 7x4 + 2x5 = 6

-2x1 + 4x2 + 5x3 + x4 = -1

7x1 - 3x2 + 2x3 - 4x4 + x5 = 8

In [ ]:
def gaussPivoteamento (A, b): #parcial
  #acessar as linhas
  for i in range(len(A)):
    #verificar maior
    pivo = math.fabs(A[i][i])
    linhaPivo = i
    for j in range (i+1,len(A)):
      if math.fabs(A[j][i])>pivo:
        pivo = math.fabs(A[j][i])
        linhaPivo = j
    #Permutar as linhas
    if linhaPivo != i:
      linhaAuxiliar = A[i]
      A[i]= A[linhaPivo]
      A[linhaPivo]=linhaAuxiliar

      bAuxiliar = b[i]
      b[i]=b[linhaPivo]
      b[linhaPivo]=bAuxiliar

    #Elimação de Gauss
    for m in range (i+1, len(A)):
      multiplicador = A[m][i]/A[i][i]
      for n in range(i, len(A)):
        A[m][n]-= multiplicador*A[i][n]
      b[m] -= multiplicador*b[i]
  #Printar
  for k in range(len(A)):
      print(A[k])
  print()
  print(b)
  print()
  calculaSolucao (A,b)

def gaussSemPivoteamento (A, b): #sem pivotamento
  for i in range(len(A)):
    if A[i][i] == 0:
      return "Erro: primeiro elemento possui o valor zero"
    else:

    #Elimação de Gauss
        for m in range (i+1, len(A)):
          multiplicador = A[m][i]/A[i][i]
          for n in range(i, len(A)):
            A[m][n]-= multiplicador*A[i][n]
          b[m] -= multiplicador*b[i]
#Printar
  for k in range(len(A)):
    print(A[k])
    print()
    print(b)
    print()
    calculaSolucao (A,b)

def calculaSolucao(A, b):
  vetorSolucao = []
  for i in range(len(A)):
    vetorSolucao.append(0)
  linha = len(A)-1
  while linha>=0:
    x = b[linha]
    coluna = len(A)-1
    while coluna > linha:
      x-=A[linha][coluna]*vetorSolucao[coluna]
      coluna -= 1
    x/=A[linha][linha]
    linha -= 1
    vetorSolucao[coluna]=x
  for j in range(len(vetorSolucao)):
    print ("x"+str(1+j)+"="+str(vetorSolucao[j]))

In [ ]:
gaussPivoteamento([[0,1,3,2,4],[8,-2,9,-1,2],[5,1,1,7,2],[-2, 4,5,1,0],[7,-3,2,-4,1]],[3,-5,6,-1,8])

[8, -2, 9, -1, 2]
[0.0, 3.5, 7.25, 0.75, 0.5]
[0.0, 0.0, -9.285714285714286, 7.142857142857142, 0.42857142857142855]
[0.0, 0.0, 0.0, -5.384615384615384, -0.7230769230769231]
[0.0, 0.0, 0.0, 0.0, 3.564285714285714]

[-5, -2.25, 10.571428571428571, 7.830769230769231, 8.335714285714285]

x1=2.3474949899799595
x2=4.3543086172344685
x3=-2.3907815631262523
x4=-1.7683366733466936
x5=2.338677354709419


In [ ]:
gaussSemPivoteamento([[0,1,3,2,4],[8,-2,9,-1,2],[5,1,1,7,2],[-2, 4,5,1,0],[7,-3,2,-4,1]], [3,-5,6,-1,8])

'Erro: primeiro elemento possui o valor zero'

**exercicio 2**


a) 

2 2 1

3 3 2

3 2 1

In [ ]:

# LU
def LU(A):
  n = len(A)
  x = [0]*n
  # Pivos
  for k in list(range(1, n, 1)):
    for i in list(range(k+1, n, 1)):
      m = A[i-1][k-1] / A[k-1][k-1]
      A[i-1][k-1] = round(m, 5)
      for j in list(range(k+1, n+1, 1)):
        A[i-1][j-1] = A[i-1][j-1] - m * A[k-1][j-1] 
        A[i-1][j-1] = round(A[i-1][j-1], 5)
  return 

A = LU([[2, 2, 1], [3, 3, 2], [3, 2, 1,]])
print("A =", A)


A = None


b) 

3 2 1

2 2 1

3 3 2

In [ ]:
# LU
def LU(A):
  n = len(A)
  x = [0]*n
  # Pivos
  for k in list(range(1, n, 1)):
    for i in list(range(k+1, n+1, 1)):
      m = A[i-1][k-1] / A[k-1][k-1]
      A[i-1][k-1] = round(m, 5)
      for j in list(range(k+1, n+1, 1)):
        A[i-1][j-1] = A[i-1][j-1] - m * A[k-1][j-1] 
        A[i-1][j-1] = round(A[i-1][j-1], 5)
  return A

A = LU([[3, 2, 1], [2, 2, 1], [3, 3, 2]])
print("A =", A)

A = [[3, 2, 1], [0.66667, 0.66667, 0.33333], [1.0, 1.49999, 0.50001]]


c) 

2 1 3

4 3 8

6 7 17

In [ ]:
# LU
def LU(A):
  n = len(A)
  x = [0]*n
  # Pivos
  for k in list(range(1, n, 1)):
    for i in list(range(k+1, n+1, 1)):
      m = A[i-1][k-1] / A[k-1][k-1]
      A[i-1][k-1] = round(m, 5)
      for j in list(range(k+1, n+1, 1)):
        A[i-1][j-1] = A[i-1][j-1] - m * A[k-1][j-1] 
        A[i-1][j-1] = round(A[i-1][j-1], 5)
  return A

A = LU([[2, 1, 3], [4, 3, 8], [6, 7, 17]])
print("A =", A)

A = [[2, 1, 3], [2.0, 1.0, 2.0], [3.0, 4.0, 0.0]]


**Exercicio 3**

3. Resolva o SELA pelo método de Fatoração de Cholesky, retendo, durante as
eliminações, cinco algarismos depois da vírgula.

x1+ 2x2 - 3x3 + 3x5 = 17

2x1 + 5x2 - x3 + x4 + 4x5 = 41

-3x1 - x2 + 50x3 + x4 - 19x5 = -45

x2 + x3 + 6x4 = 30

3x1 + 4x2 -19x3 + 39x5 = 51

In [ ]:
# cholesky
def cholesky (a):
  a = np.array(a, float)
  L = np.zeros_like(a)
  n,_=np.shape(a)
  for j in range (n):
    for i in range (j, n):
      if i == j:
        L[i,j]= np.sqrt(a[i,j]-np.sum(L[i,:j]**2))
      else:
        L[i,j]= (a[i,j]-np.sum(L[i,:j]*L[j,:j])) / L[j,j]
  return L


In [ ]:
def solveL (L, b):
  n = len(b)
  y = [0] * n
  for i in list(range(1, n+1, 1)):
    s = 0
    for j in list(range(1, i, 1)):
      s = s + L[i-1][j-1] * y[j-1]
    y[i-1] = b[i-1] - s
    y[i-1] = round(y[i-1], 5)
  return y
def solveU (U, b):
  n = len(b)
  x = [0] * n
  x[n-1] = b[n-1] / U[n-1][n-1]
  for i in list(range(n-1, 0, -1)):
    s = 0
    for j in list(range(i+1, n+1, 1)):
      s = s + U[i-1][j-1] * x[j-1]
    x[i-1] = (b[i-1]-s) / (U[i-1][i-1])
    x[i-1] = round(x[i-1], 5)
    x[i] = round(x[i], 5)
  return x

In [ ]:
A = cholesky([[1,2,-3,0,3], [2,5,-3,1,4], [-3,-1,50,1,-19], [0,1,1,6,0], [3,4,-19,0,39]])
print('x = ', A)

y = solveL (A, [17,41,-45,30,51])
print('y = ', y)

x = solveU (np.transpose(A), y)
print("x =", x)

x =  [[ 1.  0.  0.  0.  0.]
 [ 2.  1.  0.  0.  0.]
 [-3.  5.  4.  0.  0.]
 [ 0.  1. -1.  2.  0.]
 [ 3. -2.  0.  1.  5.]]
y =  [17, 7.0, -29.0, -6.0, 20.0]
x = [-145.5, 62.5, -8.5, -5.0, 4.0]


**Exercicio 4**


4. Considere cada um dos seguintes SELAs:

a)
x1 - 0.5x2 + 0.5x3 = 3

x1 + x2 + x3 = 12

-0.5x1 - 0.5x2 + x3 = 3


b)
10 x1 + 2x2 - 3x3 + 5x4 = 48

x1 + 8x2 - x3 + 2x4= 4

2x1 - x2 - 5x3 + x4= -11

-x1 + 2x2 + 3x3 + 20x4= 150

Resolva-os usando os métodos de Gauss-Jacobi e Gauss-Seidel e verifique a
convergência dos métodos. Justifique os resultados obtidos.

a) x = (2, 4, 6)
Te b) x = (3, -1, 5, 7)
T

In [ ]:
# Gauss-Seidel
def gaussSeidel (A, b, vetorSolucao, iteracoes):
  iteracao = 0
  while iteracao < iteracoes:
    for i in range(len(A)):
      x = b[i]
      for j in range(len(A)):
        if i != j:
          x -= A[i][j] * vetorSolucao[j]
      x /= A[i][i]
      vetorSolucao[i] = x
    iteracao += 1
  print(vetorSolucao)

# Gauss-Jacobi
def gaussJacobi (A, b, vetorSolucao, iteracoes):
  iteracao = 0
  vetorAux = []
  for k in range(len(vetorSolucao)):
    vetorAux.append(0)
  while iteracao < iteracoes:
    for i in range(len(A)):
      x = b[i]
      for j in range(len(A)):
        if i != j:
          x -= A[i][j] * vetorSolucao[j]
      x /= A[i][i]
      vetorAux[i] = x
    iteracao += 1
    for p in range(len(vetorAux)):
      vetorSolucao[p] = vetorAux[p]
  print(vetorSolucao)


In [ ]:
# a)
gaussJacobi([[1, -0.5, 0.5, 2], [1, 1, 1, 4], [-0.5, -0.5, 1, 6]], [3, 12, 3], [0, 0, 0], 10)

[15.427734375, 8.8828125, 16.986328125]


In [ ]:
# a)
gaussSeidel([[1, -0.5, 0.5, 2], [1, 1, 1, 4], [-0.5, -0.5, 1, 6]], [3, 12, 3], [0, 0, 0], 10)

[2.05078125, 3.9375, 5.994140625]


In [ ]:
# b)
gaussJacobi([[10, 2, -3, 5, 3], [1, 8, -1, 2, -1], [2, -1, -5, 1, 5], [-1, 2, 3, 20, 7]], [48, 4, -11, 150], [0, 0, 0, 0], 10)

[2.9998865560000008, -1.0000125825078123, 4.999891324296875, 7.0000272197203115]


In [ ]:
# b)
gaussSeidel([[10, 2, -3, 5, 3], [1, 8, -1, 2, -1], [2, -1, -5, 1, 5], [-1, 2, 3, 20, 7]], [48, 4, -11, 150], [0, 0, 0, 0], 10)

[2.999999993047814, -1.0000000030096816, 4.999999998133795, 7.000000000233291]
